
TYPE
	STATE_PART_LOADING : 
		(
		ST_LD_TO_ZERO_POS_1,
		ST_LD_TO_ZERO_POS_2,
		ST_LD_SET_AXIS_PARAMS_1,
		ST_LD_FIND_LOADING_TARGET,
		ST_LD_SERVO_MOVE_FAST,
		ST_LD_SET_AXIS_PARAMS_2,
		ST_LD_SERVO_MOVE_SLOW,
		ST_LD_UPDATE_BUFFER_INFO_1,
		ST_LD_UPDATE_BUFFER_INFO_2,
		ST_LD_DELAY,
		ST_LD_ERROR
		);
	STATE_PART_UNLOADING : 
		(
		ST_UNLD_TO_ZERO_POS_1,
		ST_UNLD_TO_ZERO_POS_2,
		ST_UNLD_SET_AXIS_PARAMS_1,
		ST_UNLD_IF_UNLOAD_CMD,
		ST_UNLD_FIND_UNLOADING_TARGET,
		ST_UNLD_SET_AXIS_PARAMS_2,
		ST_UNLD_SERVO_MOVE_TO_TARGET,
		ST_UNLD_SET_AXIS_PARAMS_3,
		ST_UNLD_SERVO_MOVE_SLOW,
		ST_UNLD_UPDATE_BUFFER_INFO,
		ST_UNLD_DELAY,
		ST_UNLD_ERROR
		);
	HolderData : 	STRUCT 
		usiSeqNumber : USINT;
		usiPartId : USINT;
	END_STRUCT;
	ServoState : 	STRUCT 
		Active : BOOL;
		MoveActive : BOOL;
		PowerON : BOOL;
		Error : BOOL;
	END_STRUCT;
END_TYPE
